#project_name: docker-swarm-project

version: '3.8'

services:
  api:
    container_name: docker-webapi-container
    build:
      context: .
      dockerfile: SakilaWebApi/Dockerfile.webapi
    image: docker-webapi-image
    restart: unless-stopped
    networks:
      - db-net
      - log-net
    ports:
      - 8080:80
    depends_on:
      - "db"
      - "seq"
    deploy:
      mode: replicated
      placement:
        constraints: 
          - node.role == manager
  db:
    container_name: docker-mssql-container
    build:
      context: ./DatabaseLibrary
      dockerfile: Dockerfile.mssql
    image: docker-mssql-image
    volumes:
      - dbdata:/var/opt/mssql
    env_file:
      - docker-mssql.env
    restart: unless-stopped
    ports:
      - 1433:1433
    networks:
      - db-net
    deploy:
      mode: replicated
      placement:
        constraints: 
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
  seq:
    container_name: docker-seq-container
    build:
      context: .
      dockerfile: Dockerfile.seq
    image: docker-seq-image
    ports:
      - 5341:80
    env_file:
      - docker-seq.env
    restart: unless-stopped
    volumes:
      - ./seqdata:/data
    networks:
      - log-net
    deploy:
      mode: replicated
      labels: 
        - name=SEQ
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: 
          - node.role == manager

networks:
  db-net:
    name: docker-db-network
  log-net:
    name: docker-log-network

volumes:
  dbdata:
    name: docker-mssql-volume
  seqdata:
    name: docker-seq-volume