#stack_name: one-node-swarm

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: SakilaWebApi/Dockerfile.webapi
    image: webapi-image
    restart: unless-stopped
    networks:
      - db-net
      - log-net
    ports:
      - 8080:80
    depends_on:
      - "db"
      - "seq"
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - name=API
      placement:
        constraints: 
          - node.role == manager
  db:
    build:
      context: ./DatabaseLibrary
      dockerfile: Dockerfile.mssql
    image: mssql-image
    volumes:
      - dbdata:/var/opt/mssql
    env_file:
      - docker-mssql.env
    restart: unless-stopped
    ports:
      - 1433:1433
    networks:
      - db-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - name=DB
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          memory: 4G
      placement:
        constraints: 
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
  seq:
    build:
      context: .
      dockerfile: Dockerfile.seq
    image: seq-image
    ports:
      - 5341:80
    env_file:
      - docker-seq.env
    restart: unless-stopped
    volumes:
      - seqdata:/data
    networks:
      - log-net
    deploy:
      mode: replicated
      replicas: 1
      labels: 
        - name=SEQ
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: 
          - node.role == manager
  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer-net
    deploy:
      mode: global
      placement:
        constraints: 
          - node.platform.os == linux
  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - portainer-net
    ports:
      - 9000:9000
    depends_on:
      - "agent"
    volumes:
      - portainerdata:/data
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  db-net:
    name: db-network
  log-net:
    name: log-network
  portainer-net:
    name: portainer-network
    driver: overlay
    attachable: true

volumes:
  dbdata:
    name: mssql-volume
  seqdata:
    name: seq-volume
  portainerdata:
    name: portainer-volume