version: '3'

services:
  api:
    container_name: api-container
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    networks:
      - db-net
    ports:
      - 5001:443
    depends_on:
      - "db"
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-container
    volumes:
      - dbdata:/var/lib/sql 
    environment:
      SA_PASSWORD: My_password123
      ACCEPT_EULA: Y
    ports:
      - 5434:1433
    networks:
      - db-net

networks:
  db-net:

volumes:
  dbdata: