version: '3.8'

services:
  api:
    container_name: docker-webapi-container
    build:
      context: .
      dockerfile: Dockerfile-webapi
    image: docker-webapi-image
    networks:
      - db-net
    ports:
      - 8080:80
    depends_on:
      - "db"
  db:
    container_name: docker-mssql-container
    build:
      context: .
      dockerfile: Dockerfile-mssql
    image: docker-mssql-image
    volumes:
      - dbdata:/var/opt/mssql
    env_file:
      - docker-mssql.env
    ports:
      - 1433:1433
    networks:
      - db-net

networks:
  db-net:
    name: docker-webapi-network

volumes:
  dbdata:
    name: docker-mssql-volume
