version: '3'

services:
  api:
    container_name: docker-webapi-by-compose-container
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-webapi-by-compose
    networks:
      - db-net
    ports:
      - 8080:80
    depends_on:
      - "db"
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-container
    volumes:
      - dbdata:/var/lib/sql 
    environment:
      SA_PASSWORD: Pas123Word2022
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - 1433:1433
    networks:
      - db-net

networks:
  db-net:

volumes:
  dbdata: